/*
 * This file is generated by jOOQ.
 */
package com.example.demojooq.model;


import com.example.demojooq.model.tables.StudentSubject;
import com.example.demojooq.model.tables.Students;
import com.example.demojooq.model.tables.Subjects;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManageStudents extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>manage_students</code>
     */
    public static final ManageStudents MANAGE_STUDENTS = new ManageStudents();

    /**
     * The table <code>manage_students.student_subject</code>.
     */
    public final StudentSubject STUDENT_SUBJECT = StudentSubject.STUDENT_SUBJECT;

    /**
     * The table <code>manage_students.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>manage_students.subjects</code>.
     */
    public final Subjects SUBJECTS = Subjects.SUBJECTS;

    /**
     * No further instances allowed
     */
    private ManageStudents() {
        super("manage_students", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            StudentSubject.STUDENT_SUBJECT,
            Students.STUDENTS,
            Subjects.SUBJECTS
        );
    }
}
