/*
 * This file is generated by jOOQ.
 */
package com.example.demojooq.model;


import com.example.demojooq.model.tables.StudentSubject;
import com.example.demojooq.model.tables.Students;
import com.example.demojooq.model.tables.Subjects;


/**
 * Convenience access to all tables in manage_students.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>manage_students.student_subject</code>.
     */
    public static final StudentSubject STUDENT_SUBJECT = StudentSubject.STUDENT_SUBJECT;

    /**
     * The table <code>manage_students.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>manage_students.subjects</code>.
     */
    public static final Subjects SUBJECTS = Subjects.SUBJECTS;
}
